services:
  mysql:
    image: mysql:8.0
    container_name: nyc-311-mlops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyc311
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 10
      start_period: 20s
    volumes:
      - nyc-311-mlops_mysql_data:/var/lib/mysql

  prefect:
    image: prefecthq/prefect:2.13.6-python3.11
    container_name: nyc-311-mlops-prefect
    command: ["prefect", "server", "start"]
    ports:
      - "4200:4200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200/api || exit 1"]
      interval: 5s
      retries: 20
      start_period: 30s
    volumes:
      - nyc-311-mlops_prefect_data:/root/.prefect

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: nyc-311-mlops-mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlruns
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 5s
      retries: 15
      start_period: 20s
    volumes:
      - nyc-311-mlops_mlflow_data:/mlruns

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nyc-311-mlops-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: nyc311
      PYTHONPATH: /app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/app
      - ./tests:/app/tests
    working_dir: /app
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 5s
      retries: 10
      start_period: 15s

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: nyc-311-mlops-dashboard
    environment:
      API_URL: http://api:8000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"
    command: >
      sh -c "streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0"

volumes:
  nyc-311-mlops_mysql_data:
  nyc-311-mlops_prefect_data:
  nyc-311-mlops_mlflow_data:















