services:
  mysql:
    image: mysql:8.0
    container_name: nyc-311-mlops-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyc311
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - nyc-311-mlops_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nyc-311-mlops-api
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: nyc311
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: nyc-311-mlops-dashboard
    depends_on:
      - api
    ports:
      - "8501:8501"
    command: >
      sh -c "streamlit run app.py --server.port=8501 --server.address=0.0.0.0"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    container_name: nyc-311-mlops-mlflow
    command: >
      mlflow server --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5000
    volumes:
      - nyc-311-mlops_mlflow_data:/mlflow
    ports:
      - "5000:5000"

  prefect:
    image: prefecthq/prefect:2-latest
    container_name: nyc-311-mlops-prefect
    command: >
      sh -c "prefect server start --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
    volumes:
      - nyc-311-mlops_prefect_data:/root/.prefect

volumes:
  nyc-311-mlops_mysql_data:
  nyc-311-mlops_mlflow_data:
  nyc-311-mlops_prefect_data:












