services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nyc311
    ports:
      - "3307:3306"
    volumes:
      - nyc-311-mlops_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build:
      context: ./api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  dashboard:
    build:
      context: ./dashboard
    command: streamlit run app.py --server.port=8501
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.8.1
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --host 0.0.0.0 --port 5001
    ports:
      - "5001:5001"
    volumes:
      - nyc-311-mlops_mlflow_data:/mlflow
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  prefect:
    image: prefecthq/prefect:2.13.0-python3.11
    command: prefect orion start --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: http://0.0.0.0:4200/api
      PREFECT_ORION_UI_API_URL: http://localhost:4200/api
    volumes:
      - nyc-311-mlops_prefect_data:/root/.prefect
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always

volumes:
  nyc-311-mlops_mysql_data:
  nyc-311-mlops_mlflow_data:
  nyc-311-mlops_prefect_data:







